### ISSUE TITLE
وب سرویس پروازهای بین المللی

### ISSUE THREAD

**Issue by mahmoud-ghoochani** [Hameds/APIs-made-in-Iran#11]
وب سرویس پروازهای بین المللی برای تمام ایرلاین ها 
http://developers.gds724.com/api

**Comment by Marjani** [comment]
این سرویس ایرانی هست؟ و یا صرفا ترجمه فارسی داره؟

**Comment by gds724** [comment]
برای یک تیم ایرانی هست . و الان هم به حدود 13 کشور دنیا به صورت مستقیم ارائه خدمات میشود .

**Comment by alihesari** [comment]
جالبه این وب سرویس خیلی میتونه به وب سایت های ایرانی و گردشگری ها کمک کنه.

**Comment by Marjani** [comment]
به نظرم قبل از اضافه کردن به لیست باید ایرانی بودن پروژه احراز بشود، در توضیحات نوشته ترکیه

**Comment by Hameds** [comment]
<div dir="rtl">
@gds724  با توجه به درخواست @Marjani  سایت اصلی رو دوباره دیدم. در بخش اطلاعات تماس یعنی https://gds724.com/page/2 ، پشتیبانی مشتریان در ترکیه ذکر شده و فقط یکی از دفاتر در ایران هست. لطفاً توضیح بفرمایید، اگر سرویس در شرکت ایرانی تولید شده، لطفاً سایت و مشخصات اون شرکت رو بفرمایید جهت بررسی بیشتر

</div>
