### ISSUE TITLE
تغییر لینک API پیام رسان گپ

### ISSUE THREAD

**Issue by ehsansabet** [Hameds/APIs-made-in-Iran#12]
لینک API پیام رسان گپ تغییر کرده است.
لینک جدید:
http://my.gap.im/documents/

**Comment by ehsansabet** [comment]
لینک مستندات مربوط به بات پلتفرم و گیم سنتر پیام رسان گپ به آدرس ذیل تغییر پیدا کرده است
https://my.gap.im/doc/

**Comment by Hameds** [comment]
<div dir="rtl">

@ehsansabet ضمن تشکر، آدرس قبلی هم کار می‌کند. آیا این آدرس جدید، مربوط به بخش دیگری است؟ در هر حال می‌توانید Pull Request نیز ارسال کنید و این issue را نیز دوباره باز می‌کنم

</div>

**Comment by ehsansabet** [comment]
@Hameds  اون آدس مستندات قدیمی است و بزودی حذف خواهد شد
