### ISSUE TITLE
سایت‌های کوتاه‌کننده لینک

### ISSUE THREAD

**Issue by Hameds** [Hameds/APIs-made-in-Iran#13]
<div dir="rtl">
در لیست تعدادی سایت کوتاه‌کننده لینک هستند که در جستجوها یا معرفی بهشون رسیدم اما به نظرم API بعضی از اون‌ها صرفاً از طریق نصب یک نرم‌افزار آماده کوتاه کننده لینک ارائه شده! اگر تجربه‌ای در این زمینه دارید لطفاً به بررسی سایت‌های کوتاه‌کننده لینک در فهرست API ‌های ساخت ایران کمک کنید
</div>

**Comment by moien007** [comment]
[Opizo](https:\\opizo.com) service provides URL shortening API, please add it.

**Comment by meysamhosseini1995** [comment]
سایت کوتاه کننده لینک 
تمامی api ها رایگان و بدون محدودیت است
لینک پست من برای آن ایجاد شده است که به راحتی کاربران میتوانند تو پست من خود اینپورت کرده و از api ها استفاده کنند.
[https://lb2.ir](url)
