### ISSUE TITLE
API سایت خدمات شبکه های اجتماعی مانند اینستاگرام

### ISSUE THREAD

**Issue by mehrab-wj** [Hameds/APIs-made-in-Iran#18]
سلام خسته نباشید عزیز
این هم API سایت فورد برای خدمات شبکه های اجتماعی مثل اینستاگرام : 
https://4rd.ir/document
و کلاس نوشته شده جهت اتصال به سایت :‌
https://github.com/mehrab-wj/4rd_class

**Comment by Hameds** [comment]
لطفاً درباره امنیت و حریم شخصی سرویس، اعلام نظر کنید.

**Comment by mehrab-wj** [comment]
امنیت سرویس بسیار بالاس
برای اتصال یک توکن خاص وجود داره که هر کاربر باید تحت پروتوکل HTTPS بهش رکوست بزنه
حریم شخصی هم از مهم ترین چیز هایی هست که توش بهش اهمیت داده شده
