### ISSUE TITLE
وب سرویس پیامک کاوه نگار

### ISSUE THREAD

**Issue by j-ghadiri** [Hameds/APIs-made-in-Iran#21]
سلام عزیز
وب سرویس پیامکی کاوه نگار
https://kavenegar.com

کاوه نگار با ارائه وب‌سرویس پیامک پیشرفته برای توسعه دهندگان ،امکان ارسال و دریافت پیامک را در اغلب سرویس ها و محصولات نرم افزاری مهیا می کند. 
https://kavenegar.com/rest.html

**Comment by Hameds** [comment]
@j-ghadiri با سلام. ضمن تشکر، همانطور که در متن لیست هم گفته شده، با توجه به تعدد سرویس‌دهندگان پیامک، این دسته از وب‌سرویس‌ها در لیست قرار نمی‌گیرند

**Comment by tech-mint** [comment]
این بهترین سرویس پیامکی هست من مشتری شون هستم و اسنپ و ... همه مشتری شون هستند چرا در لیست قرار نمیدید!؟
در واقع بهترین سرویس پیامکی ایران هست کاوه نگار

**Comment by Hameds** [comment]
@tech-mint در کامنت قبلی هم توضیح داده شد. پیشتر هم در #4 درخواست شده بود و توضیح داده شد. این لیست، وب‌سرویس‌های معرفی شده را رتبه‌بندی نمی‌کند. مثلاً ما تعدادی وب‌سرویس در حوزه ارسال پوش‌نوتیفکیشن یا نقشه داریم. نمی‌گوییم فلان سرویس، بهترین است یا مشتریان بزرگی دارد. فقط مجموعه‌ای از وب‌سرویس‌های ساخته شده در ایران را معرفی می‌کنیم. حوزه پیامک، به دلیل اینکه ارائه‌کنندگان بسیار بسیار زیادی دارد، عملاً لیست را از حالت کاربردی خارج می‌کند. اگر یک سرویس‌دهنده پیامک اضافه شود، صدها سرویس‌دهنده دیگر نیز حق دارند درخواست کنند تا آن‌ها را اضافه کنیم و در این حالت، عملاً لیست تبدیل به لیست سرویس‌دهندگان پیامک می‌شود

**Comment by tech-mint** [comment]
خب میتوانید یک فایل جدید درست کنید و همه رو ببرید توی آن قسمت پیامک در صفحه جدید. بهر حال حیف هست که مخزن جامع شما سرویسی را پوشش ندهد.

این صرفا پیشنهاد بود.
موفق باشید.

@j-ghadiri زنده باد کاوه نگار!
