### ISSUE TITLE
cant access zaal api , 404 error

### ISSUE THREAD

**Issue by arashrasoulzadeh** [Hameds/APIs-made-in-Iran#23]
https://miras-tech.github.io/zaal/

**Comment by GameO7er** [comment]
their address has been changed to 
http://miras-tech.com/zaal.html
but I couldn't find any docs.

**Comment by Hameds** [comment]
@arashrasoulzadeh Thanks for reporting this. It seems that they deleted the docs repo! I will contact them to ask about the new URL

**Comment by Hameds** [comment]
Now, zaal moved to #37 (disabled APIs)
