### ISSUE TITLE
API سایت گنجور

### ISSUE THREAD

**Issue by alimalek71** [Hameds/APIs-made-in-Iran#3]
سایت گنجور مخزن اشعار سخنرانان پارسی گو
لینک گیت هاب گنجور
https://github.com/ganjoor
مخزن api
https://github.com/ganjoor/ganjoor-api

**Comment by Hameds** [comment]
<div dir="rtl">

به نظرم نسخه آنلاین deploy شده‌اش رو باید به لیست اضافه کرد. لطفاً اگر لینک نسخه آنلاین یا مستندات روی خود سایت گنجور هست اعلام بفرمایید

</div>

**Comment by alimalek71** [comment]
یه مستند برای استفاده از api توی سایت هست
http://c.ganjoor.net
