### ISSUE TITLE
API ارسال پیامک کاوه نگار

### ISSUE THREAD

**Issue by MohsenK** [Hameds/APIs-made-in-Iran#4]
سلام
ای پی ای سرویس ارسال پیامک کاوه نگار درج نشده.

http://kavenegar.com/rest.html
ممنون

**Comment by Hameds** [comment]
<div dir="rtl">

با سلام و ضمن تشکر، با توجه به اینکه تعداد ارائه‌دهنده‌های سرویس پیامک خیلی زیاده، این دسته‌بندی رو در لیست قرار نمی‌دهیم مگر اینکه خدمات خاص و منحصر به فردی رو در بستر پیامک پیاده‌سازی کرده باشند

</div>
