### ISSUE TITLE
دسته بندی خدمات

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [Hameds/APIs-made-in-Iran#45]
تعداد زیادی از api های دسته بندی نشده به نوعی ارائه دهنده خدمتی هستند
به نظرتون اضافه شدن دسته بندی خدمات می تونه کمک کنه و تعدادی از دسته بندی نشده ها رو دارای دسته بندی کنه؟

**Comment by Hameds** [comment]
<div dir="rtl">

@MahdiMajidzadeh اینطوری به نظرم یک دسته «دسته بندی نشده» جدید درست می‌کنیم. شاید اینجوری بتونیم این مساله رو حل کنیم که اگر حداقل ۲ مورد مشابه پیدا شدند که قبلاً دسته‌بندی نداشتند یک دسته‌بندی جدید براشون درست بشه و بقیه موارد که الان اسمشون در «دسته‌بندی نشده» قرار داره تغییر نام پیدا کنه به «سایر». البته نظر سایر دوستان هم مهمه

</div>

**Comment by MahdiMajidzadeh** [comment]
به طبع اگر دسته بندی یک موردی بود باید منحل بشه؟
مثل تبلیغات یا آب و هوا؟

**Comment by Hameds** [comment]
<div dir="rtl">

@MahdiMajidzadeh به نظر من آره. چون در غیر اینصورت احتمالاً به ازای هر کدام از اون‌هایی که در «دسته‌بندی نشده» قرار دارند باید یک دسته جدید بسازیم که فقط یک عضو داره. البته این نظر شخصی منه و اصراری بهش ندارم (بیشتر پیشنهاده) و خوشحال می‌شم نظر سایر دوستان رو هم بدونم

</div>

**Comment by mohammadAliMkh** [comment]
برای کتاب api  میشناسید که رایگان باشه؟
در حد معرفی جلد و توضیحات مختصر!

**Comment by Hameds** [comment]
@mohammadAliMkh نه متاسفانه
