### ISSUE TITLE
دسته‌بندی APIها

### ISSUE THREAD

**Issue by Hameds** [Hameds/APIs-made-in-Iran#5]
<div dir="rtl">

با توجه به زیاد شدن تعداد APIها، بهتر است در چند دسته‌بندی مشخص قرار گیرند که در ابتدای readme به آن‌ها لینک anchor ایجاد شود

</div>

**Comment by Hameds** [comment]
دسته‌بندی‌های پیشنهادی فعلی:

- نقشه
- پوش نوتیفیکیشن
- مالی
- پردازش متن
- کوتاه‌کننده لینک
- حمل و نقل و سفر
- پیام‌رسان
- قیمت‌ها
-  تبلیغات
-  تقویم و اوقات شرعی

**Comment by GameO7er** [comment]
لطفا دسته بندی های

- بانک
- آب و هوا

اضافه گردد.

در صورت امکان یک نمونه از دسته بندی رو انجام بدید تا با سبک ظاهری آشنا بشم و همون روال رو ادامه بدم و تکمیل کنم تا انتها

سپاس فراوان

**Comment by Hameds** [comment]
after about 2 years, finally I can close this thanks to @GameO7er
