### ISSUE TITLE
وب سرویس‌های جدید برای اضافه شدن به لیست

### ISSUE THREAD

**Issue by Mrarchitech** [Hameds/APIs-made-in-Iran#65]
سلام وقتتون بخیر، لطفا وب سرویس اکسیر (ارایه دهنده خدمات خرید و فروش ارزهای دیجیتال، قیمت لحظه ای بازار ایران) رو هم به لیستتون اضافه کنید.

آدرس سایت: https://www.exir.io
لیست API ها: https://apidocs.exir.io

**Comment by Hameds** [comment]
<div dir='rtl'>

در Pull Request #66 اضافه شد

</div>
