### ISSUE TITLE
تبدیل تاریخ ها

### ISSUE THREAD

**Issue by shahabfar** [Hameds/APIs-made-in-Iran#67]
موضوع تقویم و اوقات شرعی:
تبدیل تاریخ ها
Persia.NET Core
https://github.com/shahabfar/Persia-.NET-Core[](https://github.com/shahabfar/Persia-.NET-Core)

**Comment by Hameds** [comment]
<div dir='rtl'>

ضمن تشکر، این پروژه در قالب محتوای این مخزن که به APIهای اغلب Rest ساخت ایران اختصاص دارد قرار نمی‌گیرد

</div>
