### ISSUE TITLE
رنكينگ وب سرویس ها

### ISSUE THREAD

**Issue by P0oOOOo0YA** [Hameds/APIs-made-in-Iran#68]
با تشکر از شما بابت لیست کردن وب سرویس های ایرانی اما لیست کردن شروع کاره و اگر بخواد کسی از این لیست عملا استفاده کنه باید یک سیستم رنکینگ هم وجود داشته باشد مثلا تو یک گروه مشابه ممکنه ده ها وب سرویس باشه که داشتن سیستم رنکینگ کمک بزرگی به انتخاب برنامه نویسان می کند.

**Comment by Hameds** [comment]
ممنون از پیشنهاد شما. این کار دشواری است و نتیجه هم احتمالاً سلیقه‌ای می‌شه که باعث می‌شه عده‌ای اعتراض کنند. شاخص‌های پیشنهادی شما برای رتبه‌بندی سرویس‌ها چیست؟

**Comment by P0oOOOo0YA** [comment]
فکر می کنم مهمترین معیار شرایط دریافت وب سرویس هست مثلا تو کشور ما بجث های فینتک و اپن بنکینگ الان راه افتاده یک سری از شرکت های زیرمجموعه بانک ها شرایط رو سخت می گیرن فقط به شخص جقوقی سرویس می دن و کلی کاغذ بازی های دیگه که با روجیه فینتک سازگار نیست بعد رایگان بودن یا نبودن سرویس صحت اطلاعات و قابل اطمینان بودن آن و حجم کاری که میشه با یک وب سرویس انجام داد

**Comment by Hameds** [comment]
رایگان بودن یا نبودن در حال حاضر ثبت می‌شود، صحت اطلاعات و قابل اطمینان بودن آن و همچنین سخت بودن یا آسان بودن دریافت وب سرویس مساله کیفی است و بسته به شرایط ممکن است متفاوت باشد و بروزرسانی اطلاعات مخزن برای این شاخص‌های کیفی کار بسیار زمان‌بری است که دقت لازم را هم نخواهد داشت. همانطور که عرض شد باعث اعتراض هم می‌شود به عنوان نمونه اگر برای وب سرویسی درج شود که قابل اطمینان نیست سازندگان آن می‌توانند به این مساله اعتراض کنند. در مورد رایگان بودن یا نبودن چنین چالشی وجود ندارد.

طبق توضیحات داده شده، رتبه‌بندی با این شاخص‌ها انجام نخواهد شد.
