### ISSUE TITLE
جانشین برای مدیریت این مخزن

### ISSUE THREAD

**Issue by Hameds** [Hameds/APIs-made-in-Iran#73]
<div dir='rtl'>

این issue به صورت pin قرار خواهد گرفت.

همین ابتدا اشاره کنم که معنی این issue رفتن من از این مخزن نیست. با لطف و حمایت دوستانی که به این مخزن، ستاره داده‌اند این مخزن حالا بیشتر از 1K ستاره دارد. این باعث شده تا گیت‌هاب برای اطمینان از ادامه پیدا کردن کار، پیشنهاد انتخاب «جانشین» برای مدیریت مخزن را بدهد. اگر از دوستان کسی به موضوع نگهداری و بروزرسانی این مخزن که یک curated list محسوب می‌شود علاقه‌ای دارد لطفاً در نظرات همین issue بفرمایید.

 
![successor](https://user-images.githubusercontent.com/1385656/140562077-5caa5cd2-2a8b-46b3-8558-6aaf976e62e3.png)

</div>

**Comment by zoghal** [comment]
درود بر حامد عزیز، 
اقا منو ته لیست بزار تا اگر زمانی کسی از من خوش قول‌تر و منظم‌تر پیدا نکردی :))
ته لیست من در خدمت باشم.

**Comment by Marjani** [comment]
سلام، تشکر بابت زحمات شما
اگر شد من رو هم در انتهای صف قرار بده 
جوانتر ها در اولیت هستند :)

**Comment by debMan** [comment]
سلام خدمت شما حامد جان. 
ممنون بابیت این مدت و زحماتت
اگر فرد مناسبی انتخاب شدند، میتونم کمکشون کنم،

**Comment by Hameds** [comment]
<div dir='rtl'>

ممنونم از همه شما که داوطلب شدید  🙏  ولی چرا برای ته صف؟ :) در هر حال و ضمن تشکر یک هفته‌ای صبر می‌کنم و بعد در خدمت حداقل یکی از دوستان خواهم بود.

</div>

**Comment by seyed-sabbagh** [comment]
هستیم در خدمتتون

**Comment by alieamami** [comment]
سلام ممنون بابت تمامی زحماتتون من علاقه دارم قبول کنم ولی متاسفانه در این زمینه تجربه ای ندارم پس ترجیح میدم به پیشرفت پروژ] کمک کنم

**Comment by Hameds** [comment]
خیلی ممنون از همگی. فعلاً آقای @Marjani که پیش‌تر سابقه مشارکت در همین پروژه رو هم داشتند اضافه کردم.

پ.ن: خوشحالم که پشتیبانی راست به چپ مدتیه به گیت‌هاب اضافه شده و فقط متن کامنت رو می‌نویسیم و نیازی به اضافه کردن `div` اضافی نیست

**Comment by Marjani** [comment]
@Hameds ممنونم از شما
از امروز زمانبندی مشخصی برای کار روی پروژه می گذارم
